export type BookRegisterInput = {
    title: string,
    author: string,
    stars: string,
    synopsis: string,
    quantity: string,
    linkImagem: string,
    "ficção": boolean,
    "romance": boolean,
    "drama": boolean,
    "crônica": boolean,
    "educação": boolean,
    "autoajuda": boolean,
    "biografia/autobiografia": boolean,
    "técnico": boolean,
    "suspense/mistério": boolean,
    "literatura nacional": boolean,
    "literatura estrangeira": boolean,
    "fantasia": boolean,
    "infantojuvenil": boolean,
    "humor/comédia": boolean,
    "poesia": boolean
}